version: '3.9'

services:
  mcp-toolbox:
    build:
      context: .
      dockerfile: Dockerfile-toolbox
    ports:
      - "5001:5000"
    command: ["/toolbox", "--tools-file", "/tools.yaml", "--address", "0.0.0.0"]
    environment:
      - TOOLBOX_PORT=5000
      - TOOLBOX_HOST=0.0.0.0
      - DATABASE_URL=${POSTGRES_URL_INTERNAL}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - default

  livekit-agent:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - LIVEKIT_URL=${LIVEKIT_URL}
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
      - AZURE_DEPLOYMENT=${AZURE_DEPLOYMENT}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - OPENAI_API_VERSION=${OPENAI_API_VERSION}
      - AZURE_TTS_DEPLOYMENT=${AZURE_TTS_DEPLOYMENT}
      - AZURE_TTS_ENDPOINT=${AZURE_TTS_ENDPOINT}
      - AZURE_TTS_API_KEY=${AZURE_TTS_API_KEY}
      - AZURE_TTS_API_VERSION=${AZURE_TTS_API_VERSION}
      - DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY}
      - TOOLBOX_URL=http://mcp-toolbox:5000/mcp
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_PROJECT_ID=${GOOGLE_PROJECT_ID}
      - GOOGLE_REFRESH_TOKEN=${GOOGLE_REFRESH_TOKEN}
      - DATABASE_URL=${POSTGRES_URL_INTERNAL}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - mcp-toolbox
    networks:
      - default
    external_links:
      - ${DB_HOST}:${DB_HOST}

  volunteer-api:
    build:
      context: .
      dockerfile: Dockerfile-api
    ports:
      - "8002:8000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - default
    external_links:
      - ${DB_HOST}:${DB_HOST}

networks:
  default:
    external: true
    name: coolify