version: '3.8'

services:
  mcp-toolbox:
    image: us-central1-docker.pkg.dev/database-toolbox/toolbox/toolbox:0.16.0
    container_name: volunteer-mcp-toolbox
    ports:
      - "5000:5000"
    volumes:
      - ./tools.yaml:/app/tools.yaml
      - ./volunteers.db:/app/volunteers.db
    command: ["--tools-file", "/app/tools.yaml"]
    restart: unless-stopped
    environment:
      - TOOLBOX_PORT=5000
      - TOOLBOX_HOST=0.0.0.0
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - volunteer-network

  livekit-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: volunteer-livekit-agent
    ports:
      - "8081:8081"  
    environment:
      - LIVEKIT_URL=${LIVEKIT_URL}
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
      - AZURE_DEPLOYMENT=${AZURE_DEPLOYMENT}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - OPENAI_API_VERSION=${OPENAI_API_VERSION}
      - AZURE_TTS_DEPLOYMENT=${AZURE_TTS_DEPLOYMENT}
      - AZURE_TTS_ENDPOINT=${AZURE_TTS_ENDPOINT}
      - AZURE_TTS_API_KEY=${AZURE_TTS_API_KEY}
      - AZURE_TTS_API_VERSION=${AZURE_TTS_API_VERSION}
      - DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY}
      - TOOLBOX_URL=http://mcp-toolbox:5000
    volumes:
      - ./.env:/home/appuser/.env:ro
    depends_on:
      mcp-toolbox:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8081/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - volunteer-network

networks:
  volunteer-network:
    driver: bridge

volumes:
  volunteer_data:
    driver: local