version: '3.9'

services:
  mcp-toolbox:
    build:
      context: .
      dockerfile: Dockerfile-toolbox
    ports:
      - "5001:5000"
    command: ["/toolbox", "--tools-file", "/tools.yaml", "--address", "0.0.0.0"]
    environment:
      - TOOLBOX_PORT=5000
      - TOOLBOX_HOST=0.0.0.0
    networks:
      - default

  google-calendar-mcp:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - TRANSPORT=http
      - HOST=0.0.0.0
      - PORT=3000
      - GOOGLE_OAUTH_CREDENTIALS=/app/gcp-oauth.keys.json
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_PROJECT_ID=${GOOGLE_PROJECT_ID}
      - NODE_ENV=production
    volumes:
      - google-calendar-tokens:/root/.config/google-calendar-mcp
    command: >
      sh -c "
        echo '{\"installed\":{\"client_id\":\"'$GOOGLE_CLIENT_ID'\",\"project_id\":\"'$GOOGLE_PROJECT_ID'\",\"auth_uri\":\"https://accounts.google.com/o/oauth2/auth\",\"token_uri\":\"https://oauth2.googleapis.com/token\",\"auth_provider_x509_cert_url\":\"https://www.googleapis.com/oauth2/v1/certs\",\"client_secret\":\"'$GOOGLE_CLIENT_SECRET'\",\"redirect_uris\":[\"http://localhost\"]}}' > /app/gcp-oauth.keys.json &&
        npm install -g @cocal/google-calendar-mcp &&
        echo 'Starting Google Calendar MCP Server in HTTP mode...' &&
        echo 'OAuth credentials file created at /app/gcp-oauth.keys.json' &&
        echo 'Server will be available at http://0.0.0.0:3000' &&
        npx @cocal/google-calendar-mcp --transport http --host 0.0.0.0 --port 3000
      "
    networks:
      - default

  livekit-agent:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - LIVEKIT_URL=${LIVEKIT_URL}
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
      - AZURE_DEPLOYMENT=${AZURE_DEPLOYMENT}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - OPENAI_API_VERSION=${OPENAI_API_VERSION}
      - AZURE_TTS_DEPLOYMENT=${AZURE_TTS_DEPLOYMENT}
      - AZURE_TTS_ENDPOINT=${AZURE_TTS_ENDPOINT}
      - AZURE_TTS_API_KEY=${AZURE_TTS_API_KEY}
      - AZURE_TTS_API_VERSION=${AZURE_TTS_API_VERSION}
      - DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY}
      - TOOLBOX_URL=http://mcp-toolbox:5000/mcp
      - GOOGLE_CALENDAR_URL=http://google-calendar-mcp:3000
    depends_on:
      - mcp-toolbox
      - google-calendar-mcp
    networks:
      - default

volumes:
  google-calendar-tokens:

networks:
  default:
    external: true
    name: coolify