version: '3.9'

services:
  mcp-toolbox:
    build:
      context: .
      dockerfile: Dockerfile-toolbox
    ports:
      - "5001:5000"
    command: ["/toolbox", "--tools-file", "/tools.yaml", "--address", "0.0.0.0"]
    environment:
      - TOOLBOX_PORT=5000
      - TOOLBOX_HOST=0.0.0.0
    networks:
      - default

  livekit-agent:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - LIVEKIT_URL=${LIVEKIT_URL}
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
      - AZURE_DEPLOYMENT=${AZURE_DEPLOYMENT}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - OPENAI_API_VERSION=${OPENAI_API_VERSION}
      - AZURE_TTS_DEPLOYMENT=${AZURE_TTS_DEPLOYMENT}
      - AZURE_TTS_ENDPOINT=${AZURE_TTS_ENDPOINT}
      - AZURE_TTS_API_KEY=${AZURE_TTS_API_KEY}
      - AZURE_TTS_API_VERSION=${AZURE_TTS_API_VERSION}
      - DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY}
      - TOOLBOX_URL=http://mcp-toolbox:5000/mcp
    depends_on:
      - mcp-toolbox
    networks:
      - default

networks:
  default:
    external: true
    name: coolify